apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prod-fastapi-route
  namespace: prod
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "fastapi.local"
    - "prod.fastapi.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prod-fastapi
          port: 8000



