apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stage-fastapi-route
  namespace: stage
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "stage.fastapi.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: stage-fastapi
          port: 8000



