apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dev-fastapi-route
  namespace: dev
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "dev.fastapi.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dev-fastapi
          port: 8000


